services:
  mongo:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=neurocheckMongo
      - MONGO_INITDB_ROOT_PASSWORD=neurocheck
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u neurocheckMongo -p neurocheck --authenticationDatabase admin --quiet
      interval: 15s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/neurocheck
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  neo4j_data:

networks:
  default:
    name: neurocheck-network
